initContainers:
  - name: headlamp-kubevirt
    image: registry.naval-group.fr:5000/headlamp-kubevirt:v2
    imagePullPolicy: Always
    command: ["/bin/sh", "-c"]
    args:
      - "cp -r /plugins/headlamp-kubevirt /headlamp-plugins/"
    volumeMounts:
      - name: headlamp-plugins
        mountPath: /headlamp-plugins

volumeMounts:
  - name: headlamp-plugins
    mountPath: /headlamp/plugins

volumes:
  - name: headlamp-plugins
    emptyDir: {}
